# SwiftLint configuration for PR Status Watcher

included:
  - Sources

excluded:
  - .build

opt_in_rules:
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - empty_collection_literal
  - empty_count
  - empty_string
  - first_where
  - force_unwrapping
  - last_where
  - missing_docs
  - modifier_order
  - multiline_arguments
  - multiline_parameters
  - operator_usage_whitespace
  - overridden_super_call
  - prefer_zero_over_explicit_init
  - redundant_nil_coalescing
  - sorted_first_last
  - toggle_bool
  - unneeded_parentheses_in_closure_argument
  - vertical_whitespace_closing_braces

# Tuning
line_length:
  warning: 130
  error: 200
  ignores_comments: true
  ignores_urls: true

file_length:
  warning: 400
  error: 600

type_body_length:
  warning: 300
  error: 500

function_body_length:
  warning: 60
  error: 100

large_tuple:
  warning: 4

nesting:
  type_level: 2
  function_level: 3
